name: Features

on:
  push:
    branches: 
      - main

jobs:
  unit_test_and_coverage:
    strategy:
      matrix:
        go-version: [1.14.x]
        # go-version: [1.14.x, 1.15.x]
        # platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [ubuntu-latest]
    name: Unit Test
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Dependencies and generate mock
        run: |
          go get github.com/golang/mock/mockgen

          make vendor

          make gen_mock

      - name: Launch unit Test
        run: make unit_test
      
      - name: Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.out
          fail_ci_if_error: true
          verbose: true
      